saml_metadata:
    path:     /saml/metadata
    defaults: { _controller: HslavichOneloginSamlBundle:Saml:metadata }

saml_acs:
    path:     /saml/acs
    defaults: { _controller: HslavichOneloginSamlBundle:Saml:assertionConsumerService }

saml_login:
    path:     /saml/login
    defaults: { _controller: HslavichOneloginSamlBundle:Saml:login }

saml_logout:
    path:     /saml/logout
    defaults: { _controller: HslavichOneloginSamlBundle:Saml:singleLogoutService }
