parameters:

services:
    #onelogin_auth:
    #    class: OneLogin_Saml2_Auth
    #    arguments: [ "%hslavich_onelogin_saml.settings%"]
    #    public: true

    ae_onelogin_saml.user_provider:
        class: AE\OneLoginSamlBundle\Security\User\SamlUserProvider

    ae_onelogin_saml.saml_provider:
        class: AE\OneLoginSamlBundle\Security\Authentication\Provider\SamlProvider

    ae_onelogin_saml.saml_token_factory:
        class: AE\OneLoginSamlBundle\Security\Authentication\Token\SamlTokenFactory

    ae_onelogin_saml.saml_listener:
        class: AE\OneLoginSamlBundle\Security\Firewall\SamlListener
        parent: security.authentication.listener.abstract
        abstract: true
